
(function(){
 if(window.__OSKAR_IMPORTS_OK__)return; window.__OSKAR_IMPORTS_OK__=true;
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const safe=n=>Number(n||0)||0;
 function db(){window.DB=window.DB||{};return window.DB}
 function arr(k){let d=db();return d[k]=Array.isArray(d[k])?d[k]:[]}
 function money(n){try{return window.money?money(n):(safe(n).toFixed(2)+' '+((db().settings||{}).currency||''))}catch(e){return safe(n).toFixed(2)}}
 function save(){let d=db();d.lastLocalUpdate=new Date().toISOString();try{if(window.persist)persist();else localStorage.setItem(window.APP_KEY||'supermarket_pos_ar_v1',JSON.stringify(d));}catch(e){} if(navigator.onLine&&window.syncNow)setTimeout(()=>syncNow(false),250)}
 function uid(p){return (window.uid?window.uid(p):p+'-'+Date.now()+'-'+Math.random().toString(16).slice(2))}
 function unit(p){return p.unit||p.type||p.packaging||p.measureUnit||'وحدة'}
 function addMenu(){let side=document.querySelector('.sidebar,.drawer,.side-menu,nav'); if(!side||document.getElementById('importsMenuLink'))return; let html='<div class="menu-group imports-menu" id="importsMenuLink"><div class="menu-title">الواردات</div><div class="submenu"><a href="إضافة-واردات.html">إضافة واردات</a><a href="سجل-الواردات.html">سجل الواردات</a></div></div>'; side.insertAdjacentHTML('beforeend',html)}
 function options(a,txt){return '<option value="">اختر</option>'+a.map(x=>'<option value="'+esc(x.id)+'">'+esc(txt(x))+'</option>').join('')}
 window.onImportProductChange=function(){let p=arr('products').find(x=>x.id===$('impProduct')?.value); if(!p)return; let u=unit(p); $('impUnitNote').textContent='الوحدة المسجلة: '+u; let isCart=/كرتون|كرتونة|carton/i.test(u); $('impMode').value=isCart?'كرتونة':'وحدة'; $('unitImportBox').style.display=isCart?'none':'grid'; $('cartonImportBox').style.display=isCart?'grid':'none'}
 window.calcImportPrices=function(){let cu=safe($('impCartonUnits')?.value); let c=safe($('impCartonCost')?.value); let s=safe($('impCartonSale')?.value); if($('impUnitCostAuto'))$('impUnitCostAuto').value=cu?(c/cu).toFixed(3):''; if($('impUnitSaleAuto'))$('impUnitSaleAuto').value=cu?(s/cu).toFixed(3):''}
 window.saveImportEntry=function(){let p=arr('products').find(x=>x.id===$('impProduct')?.value); if(!p)return alert('اختر الصنف'); let sup=arr('suppliers').find(x=>x.id===$('impSupplier')?.value)||{}; let mode=$('impMode').value; let qty=0,uc=0,us=0,total=0,cartons=0,cartonUnits=0; if(mode==='كرتونة'){cartons=safe($('impCartons').value);cartonUnits=safe($('impCartonUnits').value);uc=safe($('impUnitCostAuto').value);us=safe($('impUnitSaleAuto').value);qty=cartons*cartonUnits;total=cartons*safe($('impCartonCost').value)}else{qty=safe($('impQty').value);uc=safe($('impUnitCost').value);us=safe($('impUnitSale').value);total=qty*uc} if(qty<=0)return alert('أدخل الكمية'); let accountId=$('impAccount').value; let im={id:uid('import'),date:new Date().toLocaleString(),supplierId:sup.id||'',supplierName:sup.name||'',productId:p.id,productName:p.name||'',mode,cartons,cartonUnits,quantityUnits:qty,unitCost:uc,unitSale:us,total,accountId,note:$('impNote').value||''}; arr('imports').unshift(im); p.stock=safe(p.stock||p.qty||p.quantity)+qty; p.qty=p.stock; p.quantity=p.stock; p.cost=uc; p.purchasePrice=uc; p.price=us; p.salePrice=us; let acc=arr('accounts').find(a=>a.id===accountId); if(acc)acc.balance=safe(acc.balance)-total; else {db().settings=db().settings||{}; db().settings.cashBalance=safe(db().settings.cashBalance)-total} arr('activityLog').unshift({id:uid('act'),date:im.date,type:'واردات',action:'إضافة واردات',target:p.name,details:'زيادة المخزون '+qty+' وخصم '+total}); save(); alert('تم حفظ الواردة وتحديث المخزون'); renderImportsForm()}
 window.renderImportsForm=function(){let main=$('mainCard')||document.querySelector('main .card')||document.querySelector('main')||document.body; main.innerHTML='<form class="two-col-form" onsubmit="event.preventDefault();saveImportEntry()"><div class="field"><label>اختر المورد</label><select id="impSupplier">'+options(arr('suppliers'),x=>x.name||x.phone||'مورد')+'</select></div><div class="field"><label>اختر الصنف</label><input list="productsList" placeholder="بحث باسم الصنف"><datalist id="productsList">'+arr('products').map(p=>'<option value="'+esc(p.name||'')+'"></option>').join('')+'</datalist><select id="impProduct" onchange="onImportProductChange()">'+options(arr('products'),x=>(x.name||'')+' - '+unit(x))+'</select><div id="impUnitNote" class="muted"></div></div><input type="hidden" id="impMode" value="وحدة"><div id="unitImportBox" class="full-row two-col-form"><div class="field"><label>الكمية بالوحدة</label><input id="impQty" type="number" step="0.001"></div><div class="field"><label>سعر الجملة للوحدة</label><input id="impUnitCost" type="number" step="0.001"></div><div class="field"><label>سعر البيع للوحدة</label><input id="impUnitSale" type="number" step="0.001"></div></div><div id="cartonImportBox" class="full-row two-col-form" style="display:none"><div class="field"><label>عدد الكراتين</label><input id="impCartons" type="number" step="0.001" oninput="calcImportPrices()"></div><div class="field"><label>كم وحدة بالكرتونة</label><input id="impCartonUnits" type="number" step="0.001" oninput="calcImportPrices()"></div><div class="field"><label>سعر الجملة للكرتونة</label><input id="impCartonCost" type="number" step="0.001" oninput="calcImportPrices()"></div><div class="field"><label>سعر البيع للكرتونة</label><input id="impCartonSale" type="number" step="0.001" oninput="calcImportPrices()"></div><div class="field"><label>سعر الجملة للوحدة تلقائي</label><input id="impUnitCostAuto" readonly></div><div class="field"><label>سعر البيع للوحدة تلقائي</label><input id="impUnitSaleAuto" readonly></div></div><div class="field"><label>اختيار الحساب / الصندوق</label><select id="impAccount"><option value="cash-main">صندوق الكاش</option>'+options(arr('accounts'),x=>(x.name||'حساب')+' - '+money(x.balance))+'</select></div><div class="field"><label>ملاحظة</label><input id="impNote"></div><div class="tools full-row"><button class="btn success">حفظ الواردة وترحيلها</button></div></form>'}
 window.renderImportsLog=function(){let main=$('mainCard')||document.querySelector('main .card')||document.querySelector('main')||document.body; let rows=arr('imports'); main.innerHTML='<div class="table-wrap"><table class="data-table"><thead><tr><th>التاريخ</th><th>المورد</th><th>الصنف</th><th>النوع</th><th>الكمية</th><th>جملة/وحدة</th><th>بيع/وحدة</th><th>الإجمالي</th></tr></thead><tbody>'+(rows.map(r=>'<tr><td>'+esc(r.date)+'</td><td>'+esc(r.supplierName)+'</td><td>'+esc(r.productName)+'</td><td>'+esc(r.mode)+'</td><td>'+safe(r.quantityUnits)+'</td><td>'+money(r.unitCost)+'</td><td>'+money(r.unitSale)+'</td><td>'+money(r.total)+'</td></tr>').join('')||'<tr><td colspan="8">لا توجد واردات</td></tr>')+'</tbody></table></div>'}
 const old=window.renderPage; window.renderPage=function(){addMenu(); let f=decodeURIComponent(location.pathname.split('/').pop()); if(f==='إضافة-واردات.html')return renderImportsForm(); if(f==='سجل-الواردات.html')return renderImportsLog(); return old?old.apply(this,arguments):null};
 document.addEventListener('DOMContentLoaded',()=>{addMenu();setTimeout(()=>{let f=decodeURIComponent(location.pathname.split('/').pop()); if(f==='إضافة-واردات.html')renderImportsForm(); if(f==='سجل-الواردات.html')renderImportsLog();},100)});
})();
